/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, PDV } from './types';

export const CATEGORIES = {
  "VINOS DEL AÑO": [
    { id: 'v1', name: "San Telmo Malbec", price: 2686 },
    { id: 'v2', name: "San Telmo Cabernet", price: 2686 },
    { id: 'v3', name: "San Telmo Chardonnay", price: 2686 },
    { id: 'v4', name: "Suter Malbec", price: 2606 },
    { id: 'v5', name: "Suter Cabernet", price: 2606 },
    { id: 'v6', name: "Suter Etiqueta Marrón", price: 2606 },
    { id: 'v7', name: "Suter Tardío", price: 2606 },
    { id: 'v8', name: "Alaris Malbec", price: 3127 },
    { id: 'v9', name: "Alaris Cabernet", price: 3127 },
    { id: 'v10', name: "Alaris Red Blend", price: 3127 },
    { id: 'v11', name: "Alaris Merlot", price: 3127 },
    { id: 'v12', name: "Alaris Syrah", price: 3127 },
    { id: 'v13', name: "Alaris Chardonnay", price: 3127 },
    { id: 'v14', name: "Alaris Torrontés", price: 3127 },
    { id: 'v15', name: "Alaris Sauvignon Blanc", price: 3127 },
    { id: 'v16', name: "Alaris Cosecha Dulce Blanco", price: 3127 },
    { id: 'v17', name: "Alaris Cosecha Dulce Rosé", price: 3127 },
    { id: 'v18', name: "Finca Las Moras Malbec", price: 3022 },
    { id: 'v19', name: "Finca Las Moras Cabernet", price: 3022 },
    { id: 'v20', name: "Finca Las Moras Red Blend", price: 3022 },
    { id: 'v21', name: "Finca Las Moras Merlot", price: 3022 },
    { id: 'v22', name: "Finca Las Moras Syrah", price: 3022 },
    { id: 'v23', name: "Finca Las Moras Sauvignon Blanc", price: 3022 },
    { id: 'v24', name: "Finca Las Moras Blanco Dulce", price: 3022 },
    { id: 'v25', name: "Finca Las Moras Rosado Dulce", price: 3022 },
    { id: 'v26', name: "Fair For Life Malbec", price: 3963 },
    { id: 'v27', name: "Fair For Life Cabernet", price: 3963 },
    { id: 'v28', name: "Fair For Life Chardonnay", price: 3963 },
    { id: 'v29', name: "El Bautismo Malbec", price: 3511 },
    { id: 'v30', name: "El Bautismo Cabernet", price: 3511 },
    { id: 'v31', name: "El Bautismo Blend", price: 3511 },
    { id: 'v32', name: "El Bautismo Blanco", price: 3511 },
    { id: 'v33', name: "El Bautismo Rosado", price: 3511 },
    { id: 'v34', name: "Cazador Malbec", price: 3407 },
    { id: 'v35', name: "Cazador Cabernet", price: 3407 },
    { id: 'v36', name: "Cazador Blanco Dulce", price: 3407 },
    { id: 'v37', name: "Los Árboles Malbec", price: 3482 },
    { id: 'v38', name: "Los Árboles Cabernet", price: 3482 },
    { id: 'v39', name: "Los Árboles Red Blend", price: 3482 },
    { id: 'v40', name: "Los Árboles Chardonnay", price: 3482 },
    { id: 'v41', name: "Alma Mora Malbec", price: 4318 },
    { id: 'v42', name: "Alma Mora Cabernet", price: 4318 },
    { id: 'v43', name: "Alma Mora Red Blend", price: 4318 },
    { id: 'v44', name: "Alma Mora Merlot", price: 4318 },
    { id: 'v45', name: "Alma Mora Syrah", price: 4318 },
    { id: 'v46', name: "Alma Mora Chardonnay", price: 4318 },
    { id: 'v47', name: "Alma Mora Dulce Viognier", price: 4318 },
    { id: 'v48', name: "Alma Mora Dulce Low", price: 4318 },
    { id: 'v49', name: "Alma Mora Sauvignon Blanc", price: 4318 },
    { id: 'v50', name: "Alma Mora Blend Blanco", price: 4318 },
    { id: 'v51', name: "Alma Mora Syrah Rosé", price: 4318 },
    { id: 'v52', name: "Dadá #1", price: 4105 },
    { id: 'v53', name: "Dadá #2", price: 4105 },
    { id: 'v54', name: "Dadá #3", price: 4105 },
    { id: 'v55', name: "Dadá Malbec", price: 4105 },
    { id: 'v56', name: "Dadá Cabernet", price: 4105 },
    { id: 'v57', name: "Dadá #6 Honey", price: 4105 },
    { id: 'v58', name: "Dadá #8 Chocolate", price: 4105 },
    { id: 'v59', name: "Dadá #9 Caramel", price: 4105 },
    { id: 'v60', name: "Dadá White Malbec", price: 4105 },
    { id: 'v61', name: "Elementos Malbec", price: 3757 },
    { id: 'v62', name: "Elementos Cabernet", price: 3757 },
    { id: 'v63', name: "Elementos Red Blend", price: 3757 },
    { id: 'v64', name: "Elementos Tannat", price: 3757 },
    { id: 'v65', name: "Elementos Syrah", price: 3757 },
    { id: 'v66', name: "Elementos Chardonnay", price: 3757 },
    { id: 'v67', name: "Elementos Torrontés", price: 3757 },
    { id: 'v68', name: "Elementos Torrontés Dulce", price: 3757 },
    { id: 'v69', name: "Elementos Sauvignon Blanc", price: 3757 },
    { id: 'v70', name: "Elementos Rosé", price: 3757 },
    { id: 'v71', name: "Origen Malbec", price: 4407 },
    { id: 'v72', name: "Origen Cabernet", price: 4407 },
    { id: 'v73', name: "Alma Mora Reserva Malbec", price: 5198 },
    { id: 'v74', name: "Alma Mora Reserva Cabernet", price: 5198 },
    { id: 'v75', name: "Alma Mora Reserva Blend", price: 5198 },
    { id: 'v76', name: "Alma Mora Reserva Chardonnay", price: 5198 },
    { id: 'v77', name: "Colección Malbec", price: 5486 },
    { id: 'v78', name: "Colección Cabernet", price: 5486 },
    { id: 'v79', name: "Colección Blend", price: 5486 },
    { id: 'v80', name: "Colección Chardonnay", price: 5486 },
    { id: 'v81', name: "Don David Malbec", price: 5775 },
    { id: 'v82', name: "Don David Cabernet", price: 5775 },
    { id: 'v83', name: "Don David Pinot Noir", price: 5775 },
    { id: 'v84', name: "Don David Tannat", price: 5775 },
    { id: 'v85', name: "Don David Chardonnay", price: 5775 },
    { id: 'v86', name: "Don David Sauvignon Blanc", price: 5775 },
    { id: 'v87', name: "Fond de Cave Malbec", price: 5608 },
    { id: 'v88', name: "Fond de Cave Cabernet", price: 5608 },
    { id: 'v89', name: "Fond de Cave Syrah", price: 5608 },
    { id: 'v90', name: "Fond de Cave Chardonnay", price: 5608 },
    { id: 'v91', name: "Trapiche Reserva Malbec", price: 6117 },
    { id: 'v92', name: "Trapiche Reserva Cabernet", price: 6117 },
    { id: 'v93', name: "Trapiche Reserva Red Blend", price: 6117 },
    { id: 'v94', name: "Trapiche Reserva Merlot", price: 6117 },
    { id: 'v95', name: "Trapiche Reserva Syrah", price: 6117 },
    { id: 'v96', name: "Trapiche Reserva Chardonnay", price: 6117 },
    { id: 'v97', name: "Trapiche Reserva Sauvignon Blanc", price: 6117 }
  ],
  "VINOS DE GUARDA": [
    { id: 'p1', name: "Blend Extremos Malbec", price: 10343 },
    { id: 'p2', name: "Blend Extremos Cabernet Sauvignon", price: 10343 },
    { id: 'p3', name: "Blend Extremos Malbec Cabernet Sauvignon", price: 10343 },
    { id: 'p4', name: "Blend Extremos Merlot", price: 10343 },
    { id: 'p5', name: "Blend Extremos Pinot Noir", price: 10343 },
    { id: 'p6', name: "Blend Extremos Torrontés", price: 10343 },
    { id: 'p7', name: "Don David Reserva Cabernet Sauvignon", price: 7200 },
    { id: 'p8', name: "Don David Reserva Malbec", price: 7200 },
    { id: 'p9', name: "Don David Reserva Malbec Tannat", price: 7200 },
    { id: 'p10', name: "Don David Reserva Sauvignon Blanc", price: 7200 },
    { id: 'p11', name: "Fond de Cave Reserva Malbec", price: 6962 },
    { id: 'p12', name: "Fond de Cave Reserva Cabernet Sauvignon", price: 6962 },
    { id: 'p13', name: "Fond de Cave Reserva Cabernet Franc", price: 6962 },
    { id: 'p14', name: "Fond de Cave Reserva Sauvignon Blanc", price: 6962 },
    { id: 'p15', name: "Intocables Malbec", price: 6290 },
    { id: 'p16', name: "Intocables Cabernet", price: 6290 },
    { id: 'p17', name: "Intocables Chardonnay", price: 6290 },
    { id: 'p18', name: "Intocables Red Blend", price: 6290 },
    { id: 'p19', name: "Intocables Double Malbec", price: 6290 },
    { id: 'p20', name: "Intocables Blend", price: 6290 },
    { id: 'p21', name: "Trapiche Puro Malbec", price: 7199 },
    { id: 'p22', name: "Trapiche Puro Cabernet", price: 7199 },
    { id: 'p23', name: "Trapiche Impuro Malbec", price: 7199 },
    { id: 'p24', name: "Trapiche Impuro Cabernet", price: 7199 },
    { id: 'p25', name: "Trapiche Puro Rosé", price: 6119 },
    { id: 'p26', name: "Paz Malbec", price: 8001 },
    { id: 'p27', name: "Paz Cabernet", price: 8001 },
    { id: 'p28', name: "Paz Syrah", price: 8001 },
    { id: 'p29', name: "Navarro Correas Reserva", price: 7285 }
  ],
  ESPUMANTES: [
    { id: 'e1', name: "Espumante San Telmo Extra Brut", price: 4152 },
    { id: 'e2', name: "Espumante San Telmo Dulce", price: 4152 },
    { id: 'e3', name: "Dadá Sweet #7", price: 5990 },
    { id: 'e4', name: "Dadá Orange Bitter", price: 5990 },
    { id: 'e5', name: "Dadá Sweet Maracuyá", price: 5990 },
    { id: 'e6', name: "Dadá Sidra", price: 4864 },
    { id: 'e7', name: "Navarro Correas Extra Brut", price: 8420 },
    { id: 'e8', name: "Navarro Correas Nature", price: 8420 },
    { id: 'e9', name: "Navarro Correas Dulce", price: 8420 },
    { id: 'e10', name: "Navarro Correas Rosé", price: 8420 },
    { id: 'e11', name: "Navarro Correas Lata", price: 3370 }
  ],
  "RTD": [
    { id: 'r1', name: "Frizzé Azul Bot", price: 2243 },
    { id: 'r2', name: "Frizzé Mood Purple bot", price: 2243 },
    { id: 'r3', name: "Frizzé Limoneto bot", price: 2243 },
    { id: 'r4', name: "Frizzé Pomelo bot", price: 2243 },
    { id: 'r5', name: "Frizzé Lata Azul Lata", price: 1512 },
    { id: 'r6', name: "Frizzé Lata Limoneto lata", price: 1512 },
    { id: 'r7', name: "Frizzé Lata Pomelo lata", price: 1512 },
    { id: 'r8', name: "Smirnoff Ice Berry", price: 2245 },
    { id: 'r9', name: "Smirnoff Ice Green Apple", price: 2245 },
    { id: 'r10', name: "Smirnoff Ice Original", price: 2245 },
    { id: 'r11', name: "Smirnoff BC Lime", price: 2000 },
    { id: 'r12', name: "Smirnoff BC Pomelo", price: 2000 },
    { id: 'r13', name: "Gordon’s Tonic", price: 2240 }
  ],
  "ANTARES": [
    { id: 'a1', name: "Antares Lager", price: 1931 },
    { id: 'a2', name: "Antares IPA Sin Alcohol", price: 2077 },
    { id: 'a3', name: "Antares Caravana", price: 2310 },
    { id: 'a4', name: "Antares IPA", price: 2310 },
    { id: 'a5', name: "Antares Honey", price: 2310 },
    { id: 'a6', name: "Antares Scotch", price: 2310 },
    { id: 'a7', name: "Antares Kölsch", price: 2310 },
    { id: 'a8', name: "Antares Playa Grande", price: 2310 }
  ],
  "SPIRITS": [
    { id: 's1', name: "Gordon’s", price: 11060 },
    { id: 's2', name: "Gordon’s Pink", price: 11980 },
    { id: 's3', name: "Gordon´s Tropical", price: 11980 },
    { id: 's4', name: "Smirnoff Original", price: 7093 },
    { id: 's5', name: "Smirnoff Green Apple", price: 7800 },
    { id: 's6', name: "Smirnoff Strawberry", price: 7800 },
    { id: 's7', name: "Smirnoff Watermelon", price: 7800 },
    { id: 's8', name: "Smirnoff Tropical", price: 7800 },
    { id: 's9', name: "Smirnoff Tamarindo Spicy", price: 7800 },
    { id: 's10', name: "Smirnoff Grapefruit & Lime", price: 7800 },
    { id: 's11', name: "Smirnoff Ruby Orange", price: 7800 },
    { id: 's12', name: "Smirnoff Tangerine", price: 7800 },
    { id: 's13', name: "Tanqueray Dry", price: 24390 },
    { id: 's14', name: "Tanqueray Sevilla", price: 29283 },
    { id: 's15', name: "Tanqueray Royal", price: 29283 },
    { id: 's16', name: "Johnnie Walker Red Label 750ml", price: 25440 },
    { id: 's17', name: "Johnnie Walker Red Label 1L", price: 30240 },
    { id: 's18', name: "Johnnie Walker Black Label 750ml", price: 47107 },
    { id: 's19', name: "Johnnie Walker Black Label 1L", price: 56046 },
    { id: 's20', name: "Johnnie Walker Double Black", price: 53633 },
    { id: 's21', name: "White Horse", price: 13300 },
    { id: 's22', name: "Baileys", price: 26059 },
    { id: 's23', name: "Baileys Caramel", price: 27402 }
  ]
};

export const INITIAL_CLIENTS: PDV[] = [
  { 
    id: "901-1", 
    name: "ZHENG CHANGI", 
    address: "AVDA SUAREZ 1957", 
    billing: "$ 82,868", 
    type: "AUTOSERVICIO A", 
    plans: ["CCC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CCC", "CNC", "CCC"], 
    portfolio: [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1] 
  },
  { 
    id: "901-2", 
    name: "AUT.SERV.D.C", 
    address: "PEPIRI 818", 
    billing: "$ 0", 
    type: "AUTOSERVICIO A", 
    plans: ["CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CCC", "CCC"], 
    portfolio: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1] 
  },
  { 
    id: "901-3", 
    name: "GAUNA LILIANA", 
    address: "AVDA AMANCIO ALCORTA 3330", 
    billing: "$ 54,698", 
    type: "AUTOSERVICIO A", 
    plans: ["CCC", "CCC", "CCC", "CCC", "CNC", "CCC", "CNC", "CNC", "CNC", "CNC", "CCC", "CNC"], 
    portfolio: [1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0] 
  },
  { 
    id: "901-4", 
    name: "WANG XIAOQIN", 
    address: "AVDA VELEZ SARSFIELD 1660", 
    billing: "$ 1,206,024", 
    type: "AUTOSERVICIO A", 
    plan: "SILVER",
    plans: ["CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CNC", "CCC", "CCC", "CNC"], 
    portfolio: [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0] 
  },
  { 
    id: "901-5", 
    name: "XIE PINGFENG", 
    address: "AV AMANCIO ALCORTA 3395", 
    billing: "$ 1,247,616", 
    type: "AUTOSERVICIO A", 
    plans: ["CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CNC", "CCC", "CCC"], 
    portfolio: [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1] 
  },
  { 
    id: "901-6", 
    name: "CHEN HONGYU", 
    address: "AVDA SAENZ 740", 
    billing: "$ 538,890", 
    type: "AUTOSERVICIO A", 
    plans: ["CCC", "CNC", "CCC", "CCC", "CNC", "CCC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC"], 
    portfolio: [1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0] 
  },
  { 
    id: "901-7", 
    name: "ZHENG MIANWEI", 
    address: "LUNA 472", 
    billing: "$ 315,005", 
    type: "AUTOSERVICIO A", 
    plans: ["CCC", "CNC", "CNC", "CCC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC"], 
    portfolio: [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0] 
  },
  { 
    id: "901-8", 
    name: "WANG LIQIN", 
    address: "AVDA AMANCIO ALCORTA 3676", 
    billing: "$ 219,204", 
    type: "AUTOSERVICIO A", 
    plan: "SILVER",
    plans: ["CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC"], 
    portfolio: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 
  },
  { 
    id: "901-9", 
    name: "CHEN LIAN", 
    address: "JOSE CAMILO PAZ 2977", 
    billing: "$ 0", 
    type: "AUTOSERVICIO A", 
    plans: ["CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CCC", "CNC"], 
    portfolio: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0] 
  },
  { 
    id: "901-10", 
    name: "LIN SHENGBIAO", 
    address: "FAMATINA 3547", 
    billing: "$ 0", 
    type: "AUTOSERVICIO A", 
    plans: ["CNC", "CCC", "CCC", "CNC", "CNC", "CNC", "CNC", "CCC", "CNC", "CNC", "CNC", "CNC"], 
    portfolio: [0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0] 
  },
  { 
    id: "901-11", 
    name: "YANG QIAOMING", 
    address: "HIPOLITO VIEYTES 1431", 
    billing: "$ 343,824", 
    type: "AUTOSERVICIO A", 
    plans: ["CCC", "CCC", "CCC", "CCC", "CNC", "CCC", "CCC", "CNC", "CNC", "CNC", "CCC", "CCC"], 
    portfolio: [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1] 
  },
  { 
    id: "901-12", 
    name: "XIAOMING XIE", 
    address: "IRIARTE 3375 3375", 
    billing: "$ 577,931", 
    type: "AUTOSERVICIO A", 
    plan: "INICIAL",
    plans: ["CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CNC", "CCC", "CCC", "CNC"], 
    portfolio: [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0] 
  },
  { 
    id: "901-13", 
    name: "ZHANG JINGJING", 
    address: "SANTO DOMINGO 3819", 
    billing: "$ 1,231,030", 
    type: "AUTOSERVICIO A", 
    plan: "SILVER",
    plans: ["CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC"], 
    portfolio: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 
  },
  { 
    id: "901-14", 
    name: "CHEN LINWANG", 
    address: "CALIFORNIA 2250", 
    billing: "$ 465,744", 
    type: "AUTOSERVICIO A", 
    plans: ["CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CCC"], 
    portfolio: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 
  },
  { 
    id: "901-15", 
    name: "LI XINGHUA", 
    address: "ALVARADO 2701", 
    billing: "$ 0", 
    type: "AUTOSERVICIO A", 
    plans: ["CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC", "CNC"], 
    portfolio: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 
  },
  { 
    id: "901-16", 
    name: "XIE PINGZHEN", 
    address: "PEPIRÍ 750", 
    billing: "$ 0", 
    type: "AUTOSERVICIO A", 
    plans: ["CNC", "CCC", "CCC", "CCC", "CNC", "CCC", "CCC", "CNC", "CNC", "CNC", "CNC", "CCC"], 
    portfolio: [0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1] 
  },
  { 
    id: "901-17", 
    name: "LIN CHEN", 
    address: "AV. GRAL. TOMÁS DE IRIARTE 2757", 
    billing: "$ 899,498", 
    type: "AUTOSERVICIO A", 
    plan: "INICIAL",
    plans: ["CCC", "CCC", "CCC", "CCC", "CCC", "CCC", "CNC", "CCC", "CNC", "CNC", "CCC", "CCC"], 
    portfolio: [1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1] 
  },
  { 
    id: "902-1", 
    name: "WANG XIAMEI", 
    address: "ZUVIRIA 3229", 
    billing: "$ 125,590", 
    type: "AUTOSERVICIO A", 
    plan: "SILVER",
    plans: ["CCC", "CCC", "CNC", "CCC", "CCC", "CNC", "CCC", "CCC", "CCC", "CCC", "CCC", "CNC"], 
    portfolio: [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0] 
  }
];
